name: Velog Posts GraphQL Sync

on:
  schedule:
    - cron: '30 14 * * *'   # UTC 14:30 = KST 23:30
  workflow_dispatch:        # 수동 실행 가능

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0      # 전체 커밋 히스토리 가져오기

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Cache pip packages
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/*.py') }}
        restore-keys: |
          ${{ runner.os }}-pip

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-frontmatter requests gitpython

    - name: Configure Git
      run: |
        git config --global user.name "${{ secrets.GIT_USERNAME }}"
        git config --global user.email "${{ secrets.GIT_EMAIL }}"

    - name: Run sync script
      env:
        VELOG_USERNAME: ${{ secrets.VELOG_USERNAME }}
        GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
        GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
      run: |
        success=false
        for i in {1..3}; do
          if python scripts/update_blog_graphql.py; then
            success=true
            break
          fi
          echo "Attempt $i failed. Retrying in 10 seconds..."
          sleep 10
        done

        if [ "$success" = false ]; then
          echo "All attempts failed"
          exit 1  # 명시적으로 실패 상태를 반환
        fi

    - name: Push changes
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        if git diff --quiet; then
          echo "No changes to push"
        else
          git push https://$GH_PAT@github.com/${{ github.repository }}.git
          echo "Changes pushed successfully"
        fi

    - name: Send notification on failure
      if: failure() # workflow가 실패했을 때만 실행
      uses: actions/github-script@v7
      with:
        script: |
          await octokit.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: 'Velog Sync Failed',
            body: `Sync job failed at ${new Date().toISOString()}. 
                   Please check the [workflow logs](https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}) for details.`
          })